### ISSUE TITLE
/usr/bin/env: php : No such file or directory

### ISSUE THREAD

**Issue by DrDeath72** [samdark/yii2-webshell#10]
Через шел работает `/usr/bin/env php /home/***/yii`
Через скрипт `yii` выдает `/usr/bin/env: php : No such file or directory`

**Comment by samdark** [comment]
Скорее всего у юзера, от которого работает PHP, нет достаточно прав.

**Comment by samdark** [comment]
Решится через https://github.com/samdark/yii2-webshell/issues/3

**Comment by DrDeath72** [comment]
Через юзера шелом работает

**Comment by DrDeath72** [comment]
Может open_basedir влияет? 
Хотя что так `php_admin_value open_basedir "/usr/bin/:/home/drdeath/www/:/home/drdeath/tmp/"` что закоментированно не работает...
