### ISSUE TITLE
yii migrate causes "unknown command" after "Apply? = yes" prompt

### ISSUE THREAD

**Issue by Forin** [samdark/yii2-webshell#12]
Did you test webshell with the migrate command?
I always get an "Unknown command." error after the "yes" prompt.

```
Yii 2.0 web shell
$ yii migrate
Yii Migration Tool (based on Yii v2.0.7)

Total 1 new migration to be applied:
    m160329_110000_create_modelhistory

Apply the above migration? (yes|no) [no]:
$ y
Unknown command.
```

Running the "yii migrate" command in linux shell works without problems,
so there must be something wrong with webshell or my config:

```
    'webshell' => [
        'class' => 'samdark\webshell\Module',
        'yiiScript' => '/var/www/html/myprojectfolder/yii'
   ]
```

The yiiScript is executable and works fine when run with one of the following commands:

```
   php yii
   ./yii
```

Webshell works fine as long as there is no prompt.
I don't know where to start debugging...

**Comment by samdark** [comment]
Web shell is unable to work interactively because of web request-response nature.

**Comment by Forin** [comment]
Thanks, I didn´t know the --interactive=0 Parameter, which solves the problem.
