### ISSUE TITLE
Ошибка "Invalid path alias"

### ISSUE THREAD

**Issue by artem78** [samdark/yii2-webshell#18]
Вываливается с ошибкой: `Invalid path alias: @samdark/webshell/assets`. Что делать?

**Comment by samdark** [comment]
Написать, как именно воспроизвести: что делали, что ожидали, что получилось.

**Comment by artem78** [comment]
Перезалил папку vendors, консоль появилась. Но теперь другая ошибка: ввожу команду, выводится номер версии php с заголовком content-type и больше ничего.
```
Yii 2.0 web shell
$ yii help
X-Powered-By: PHP/5.5.38
Content-Type: application/json; charset=UTF-8
$ yii migrate
X-Powered-By: PHP/5.5.38
Content-Type: application/json; charset=UTF-8
$  

```

**Comment by samdark** [comment]
Ничем не могу тут помочь. У меня вроде работает. Разбирайтесь, почему не работает у вас...

**Comment by anton6378** [comment]
Столкнулся с таким же поведением. Перезалил вендорс. 
Утилита никак не возвращает визуальной ошибки, когда на сервере не установлен php cli. Так бывает на некоторых хостингах.
