### ISSUE TITLE
Configure with Yii Starter Kit

### ISSUE THREAD

**Issue by rickgrana** [samdark/yii2-webshell#19]
Hello,

I am trying to use trntv/yii2-starter-kit with Webshell, but I can't configure it.

When I type yii help I get no message

I am trying to configure yiiScript with 

'yiiScript' => Yii::getAlias('@common'). '/yii',
'yiiScript' => Yii::getAlias('@backend'). '/yii',

But with no success

**Comment by samdark** [comment]
Github issue tracker isn't a support forum. Please ask either at official forums or in Slack: https://join.slack.com/t/yii/shared_invite/MjIxMjMxMTk5MTU1LTE1MDE3MDAwMzMtM2VkMTMyMjY1Ng
