### ISSUE TITLE
Scroll to bottom after command execution

### ISSUE THREAD

**Issue by iushev** [samdark/yii2-webshell#2]
When output from command execution is long it is not visible. Need to scroll to see result.
I test in Chrome and Firefox.

**Comment by SDKiller** [comment]
:+1: 

Also it would be nice to scroll command line into view when pressing arrows, backspace

**Comment by YaroslavShapoval** [comment]
I think it is the [jquery.terminal](https://github.com/jcubic/jquery.terminal) problem, this issue couldn't be solved without changing jquery.terminal library.

**Comment by samdark** [comment]
I think it could be solved w/o changing it. We know when the command is executed so the only thing left is to figure out how to scroll down.

**Comment by YaroslavShapoval** [comment]
You're right, and I did not put it quite right. I mean that I did not found in the library jquery.terminal of the method by which it would be possible to catch the launch command. Sure it possible just catch enter key manually.
