### ISSUE TITLE
Can't install package because of bower-asset dependency issue

### ISSUE THREAD

**Issue by hdnarola** [samdark/yii2-webshell#20]
The package was install earlier but suddenly when ran composer update then below dependencies problems are there :

```
  Problem 1
    - Root composer.json requires samdark/yii2-webshell ~2.0 -> satisfiable by samdark/yii2-webshell[2.0.0].
    - samdark/yii2-webshell 2.0.0 requires bower-asset/jquery.terminal ~0.8.8 -> found bower-asset/jquery.terminal[dev-master, 2.23.1, ..., 2.35.3] but it does not match the constraint.
```

Also tried installing this package with composer require but same output
Ref 1 : https://prnt.sc/qIlVdaRtX11K
Ref 2 : https://prnt.sc/Eop72TyyX9-J

Is there any additional config require?

**Comment by hdnarola** [comment]
@samdark would you please have a look into it?

**Comment by samdark** [comment]
Fixed.

**Comment by hdnarola** [comment]
Thanks, Now working.

**Comment by hdnarola** [comment]
Hello @samdark 
I really appreciate the quick Fix.

But I've a query out of curiosity that : 
- Is it possible to upgrade the package's dependency **"bower-asset/jquery.terminal"** to latest version? (**i.e.** ~0.8.8 to ^2.35.3)
- Asking this as there're some other packages that supports latest version & its not possible to install them along with this package as per this dependency
- **Dependency Ref** : https://prnt.sc/5z0DiNfaQ4kc

Looking forward to your reply.

**Comment by samdark** [comment]
> Is it possible to upgrade the package's dependency "bower-asset/jquery.terminal" to latest version? (i.e. ~0.8.8 to ^2.35.3)

I have no idea. Try it.
