### ISSUE TITLE
Problem updating/installing (issue #20 doesn't seem to be resolved

### ISSUE THREAD

**Issue by ynzejan** [samdark/yii2-webshell#21]
Problem 1
    - Root composer.json requires bower-asset/jquery.terminal, it could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Root composer.json requires samdark/yii2-webshell ~2.0 -> satisfiable by samdark/yii2-webshell[2.0.0].
    - samdark/yii2-webshell 2.0.0 requires bower-asset/jquery.terminal ~0.8.8 -> could not be found in any version, there may be a typo in the package name.

On April 19 this issue was closed, however it reappears.

**Comment by samdark** [comment]
Can't reproduce:

1. Installed `yii2-app-basic` including running `composer install`.
2. `composer require samdark/yii2-webshell`

<img width="562" alt="image" src="https://github.com/samdark/yii2-webshell/assets/47294/9f026f32-d799-420a-92bc-99b07c8ae15a">
