### ISSUE TITLE
Package bower-asset/jquery.terminal not found

### ISSUE THREAD

**Issue by ErcikKtm** [samdark/yii2-webshell#22]
I've tried to install the webshell plugin for run some scripts in a project, but i had a problem when i tried to run the command:

`composer require --prefer-dist samdark/yii2-webshell "~2.0"`

The error message that i had was:

```
Problem 1
    - Root composer.json requires samdark/yii2-webshell ~2.0 -> satisfiable by samdark/yii2-webshell[2.0.0].
    - samdark/yii2-webshell 2.0.0 requires bower-asset/jquery.terminal ~0.8.8 -> could not be found in any version, there may be a typo in the package name.

```

Do you have an idea to solve this? Is there another package that can replace the missing?

**Comment by samdark** [comment]
Interesting. The package is there: https://asset-packagist.org/package/detail?fullname=bower-asset/jquery.terminal

**Comment by samdark** [comment]
Just installed it:

<img width="502" alt="image" src="https://github.com/samdark/yii2-webshell/assets/47294/82f3d781-4d1d-45fb-b999-619460586b59">

Do you use asset packagist in your app? https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json#L68
