### ISSUE TITLE
Не работает на advanced версии

### ISSUE THREAD

**Issue by ddis** [samdark/yii2-webshell#5]
WebShell не работает на advanced версии yii2, на basic работает. Там ошибка с алиасом @app, для advanced это не корень сайта, а backend или frontend. Если в модуле (Module.php) заменить $yiiScript @app на свой алиас, который который будет вести на корень (где лежит файл yii) все начинает работать.

**Comment by samdark** [comment]
Так и задумано. Свойство public, настраивается из конфига: https://github.com/samdark/yii2-webshell/blob/master/Module.php#L45

**Comment by samdark** [comment]
https://github.com/samdark/yii2-webshell/commit/fe8116440430b1748c3069128347741d58326465
