### ISSUE TITLE
Не работает подтверждение операции. 

### ISSUE THREAD

**Issue by ddis** [samdark/yii2-webshell#6]
При попытке создать/провести миграцию идет запрос на подтверждение. 
Если ответить на запрос, выдает Unknown command.
$ yii migrate
Yii Migration Tool (based on Yii v2.0.6)

Total 1 new migration to be applied:
    m150826_060922_test

Apply the above migration? (yes|no) [no]:
$ yes
Unknown command.

курсор автоматически переносит.

**Comment by andjelko** [comment]
same problem to me!

**Comment by samdark** [comment]
Yep. It can't hold command execution. I doubt it could be solved. Run commands in non-interactive mode.

**Comment by andjelko** [comment]
How to do that?

Cheers,
Milos

**Comment by samdark** [comment]
By adding `--interactive=0` to the command.

**Comment by andjelko** [comment]
Thanks
