### ISSUE TITLE
Nothing happen about commands

### ISSUE THREAD

**Issue by zhukovsergei** [samdark/yii2-webshell#8]
Приветствую!
Я недавно подсел на Yii2 и есть вопрос с консолькой.
Нет доступа к по ssh к серверу, поэтому нашел Ваше решение.
У меня установлен yii2-advanced template
Если я правильно понимаю, то сам модуль ссылается на скриптовой файл yii
Этот скрипт лежит в корне директории.
В конфиге прописал:
'modules' => [
    'webshell' => [
      'class' => 'samdark\webshell\Module',
      'allowedIPs' => ['*'],
       'yiiScript' => '@root',
    ],
  ],
Все подключилось, но при выполнении команд ничего не происходит:
![image](https://cloud.githubusercontent.com/assets/1946769/10409834/b4637c7e-6f50-11e5-869b-0bd03b33f6b3.png)

**Comment by zhukovsergei** [comment]
у меня задача, выполнить миграцию

**Comment by samdark** [comment]
`@root/yii`?

**Comment by zhukovsergei** [comment]
Все также ;(
